<h1>Tratamento de erros no TypeScript - Exceptions</h1>



Componentes de software podem ter problemas durante a execução e gerar erros como:

- Terminar o programa inesperadamente;
- Retornar uma mensagem de erro indicando uma falha;
- Retornar e/ou ignorar uma falha ou um erro;
- Chamar um método para tratar o erro, entre outras possibilidades.

Os problemas mais comumente encontrados são:

- Falha na aquisição de um recurso (Criar um recurso, Abrir um recurso...);
- Tentativa de fazer algo impossível (Divisão por zero, Passar um valor para uma variável diferente do esperado...);
- Outras condições inválidas (Ultrapassar o limite da memória...).

Para contornar estes empecilhos, utilizamos as estruturas de Tratamento de Erros, conhecidas como **Exceções (Exceptions)**.

<br />

<h2>1. Exceptions</h2>



As **Exceções** (Exceptions) são uma indicação de um problema que ocorre durante a execução de um programa, ou seja, são eventos que interrompem o fluxo normal de processamento de uma Classe, Método ou Função, causando um erro na aplicação. 

Na Linguagem TypeScript, é possível tratar as exceções, que normalmente interromperiam a execução da aplicação, de forma que o programa continue funcionando ou termine de forma elegante, tornando o código muito mais robusto e confiável.

As Exceções na Linguagem TypeScript são Objetos criados a partir de Classes especiais, que são “disparados” quando ocorrem condições excepcionais durante a execução do código. 

<br />

<h3>1.1 Tipos de Erros</h2>



Os erros que acontecem nas aplicações TypeScript estão classificados em 3 categorias:


1. **Erros de lógica:** Esta categoria abrange erros na construção do Algoritmo. Este tipo de erro devem ser corrigidos pelo programador

  **Exemplos:** 

  - Ultrapassar os Limites do vetor; 
  - Dividir um número por zero;
  - Entre outros.

2. **Erros do ambiente de execução:** Esta categoria abrange erros na infraestrutura onde a aplicação está sendo executada. Este tipo de erro foge do controle da pessoa desenvolvedora, mas podem ser contornados em tempo de execução;

  **Exemplos:** 

  - Arquivo não encontrado;
  - Rede fora de operação;
  - Link de Internet off-line;
  - Entre outros;

3. **Erros graves:** São os erros que simplesmente travam o sistema e não há nada o que fazer. Este tipo de erro também foge do controle da pessoa desenvolvedora e não podem ser contornados;

	**Exemplos:** 
	
	- Falta de memória;
	- Erro de disco;
	- Erro interno do TypeScript;
	- Entre outros.

As Exceções tem como foco principal tratar os erros do tipo 1, ou seja, erros de lógica, como veremos no exemplo abaixo:

<br />

<img src="https://i.imgur.com/8eYS3Y6.png" title="source: imgur.com" width="3%"/>**Exemplo 01 - Exibir uma string em Letras Maiúsculas:** 

```ts
const resultado = converte(123);

console.log(resultado);

export function converte(conteudo: any): string{
    return conteudo.toUpperCase();
}
```

O código acima, é um programa simples, que tenta exibir uma string com todas as letras maiúsculas. O que será que acontecerá se passarmos um número, ao invés de uma string?

<img src="https://i.imgur.com/V2ReOnx.png" title="source: imgur.com" width="3%"/>**Resultado do Algoritmo:**

<div align="center"><img src="https://i.imgur.com/pUvhdfS.png" title="source: imgur.com" /></div>

No resultado acima, vemos que foi disparada uma exceção: **TypeError** (indicado por uma seta amarela), informando que aconteceu algum erro ao tentar converter a string para letras maiúsculas e na sequência o programa é finalizado sem dar a oportunidade de contornar o erro. No exemplo acima, a exceção indica que não é possível efetuar a conversão de um número para letras maiúsculas.

Quando uma exceção é lançada sem nenhum tipo de tratamento, ela interrompe o **fluxo normal** do programa, como vimos no exemplo acima. Se o método onde o erro aconteceu não capturar a exceção, ela será **propagada** para o método que chamar esse método e assim por diante. Se **ninguém** capturar a exceção, ela causará o término da aplicação. Agora se em algum lugar ela for capturada, **o controle da aplicação pode ser recuperado**.

Um bom **Sistema de Tratamento de Exceções** procura sempre atender a 3 princípios fundamentais: 

- Se antecipar aos problemas (uma das tarefas da pessoa desenvolvedora);
- Reverter situações de erro que podem ser revertidas;
- Buscar a **Solução ideal** para o tratamento de problemas de forma isolada do código principal.

Com o tratamento de exceções, o programa captura e trata o erro, isto é, lida com a exceção. Para capturar e lidar com as exceções o TypeScript utiliza a estrutura **try-catch-finally**.

<br />

<h2>2. Estrutura try-catch-finally</h2>



A estrutura **try-catch-finally** é utilizada pelo TypeScript para capturar e tratar um erro ou exceção. Ela é composta por 3 estruturas básicas:

- **try:** é usada para indicar um bloco de código que possa lançar (throw) uma exceção. Caso ocorra uma exceção em algum ponto, o restante do código contido no bloco <em>try</em> não será executado. O bloco <em>try</em> não pode ser declarado sozinho, portanto, precisa estar seguido de um ou vários blocos <em>catch</em> e/ou de um bloco <em>finally</em>.
- **catch:** serve para capturar as exceções e tratar o erro. Esse bloco será executado somente se o bloco <em>try</em> apresentar alguma exceção. Numa estrutura try-catch-finally você pode criar apenas um bloco <em>catch</em> e para  identificar o tipo da exceção utilizaremos um laço condicional.
- **finally:** é um bloco opcional, mas caso seja construído, ele sempre será executado, a menos que seja forçada sua parada, por exemplo, com o comando **process.exit(0)**, que força a finalização da aplicação TypeScript, na instrução catch. Geralmente utilizamos o bloco finally quando precisamos executar algum código, independente se ocorrer a Exception ou não.

**Sintaxe:**

```ts
try {
	// Instruções que podem causar uma Exception
} catch (error) {
	// Implementação do Bloco Catch - Caso Ocorra a Exception
} finally {
	// Implementação do Bloco Finally (opcional)
}
```

O **Bloco try** contém o código que pode lançar (throw) uma exceção. Ele consiste na palavra – chave try seguida por um bloco de código entre chaves.

O **Bloco Catch** captura e trata as exceções. Ele começa com a palavra-chave catch. Dentro dos parênteses deve ser inserido um parâmetro do tipo any, geralmente nomeado como **e** ou **error**, que será utilizado para identificar o tipo da exceção, ou seja, o tipo do erro. O bloco de código entre as chaves será executado quando uma exceção acontecer, ou seja, o que fazer em caso de erro. Para definir ações específicas para cada tipo de erro, utilizaremos um Laço Condicional em conjunto com a instrução **instanceof**, que verifica qual é o tipo do erro que foi capturado pelo parâmetro **error**.

O **Bloco Finally** é um Bloco opcional, Caso seja construído, quase sempre ele será executado. Geralmente ele contém código de liberação de recursos do sistema. **Exemplo:** finalizar a conexão com uma Banco de dados

<br />

<h3>2.1 O comando de Saída console.error()</h3>



O comando de Saída **console.error()** funciona da mesma forma que o comando de Saída **console.log()**. A principal diferença é que este comando é usado principalmente para exibir as mensagens relacionadas aos erros de exceção capturadas pela instrução **catch** no console. Dependendo das configurações do seu console, a mensagem poderá ser exibida na cor vermelha, para tornar mais óbvio que é uma mensagem de erro.

<br />

<img src="https://i.imgur.com/8eYS3Y6.png" title="source: imgur.com" width="3%"/>**Exemplo 02 - Exibir uma string em Letras Maiúsculas com tratamento de exceções - versão 01:** 

Vamos implementar o tratamento de exceções no exemplo 01:

```ts
try {
    
    const resultado = converte(123);

    console.log(resultado);

} catch (error) {
     console.log(Object.getPrototypeOf(error));
}

export function converte(conteudo: any): string{
    return conteudo.toUpperCase();
}
```

<img src="https://i.imgur.com/V2ReOnx.png" title="source: imgur.com" width="3%"/>**Resultado do Algoritmo:**

```bash
[Error [TypeError]]
```

Observe no resultado acima que a exceção: **TypeError** foi disparada, mas desta vez não foi exibida a lista toda de erros. O Bloco Catch apenas indicou o tipo de erro que foi disparado, porque utilizamos a instrução **Object.getPrototypeOf()**, que identifica o tipo do erro disparado.

Na sequência, vamos personalizar a mensagem de erro da exceção e implementar o Bloco Finally:

<img src="https://i.imgur.com/8eYS3Y6.png" title="source: imgur.com" width="3%"/>**Exemplo 03 - Exibir uma string em Letras Maiúsculas com tratamento de exceções - versão 02:** 

```ts
try {
    
    const resultado = converte(123);

    console.log(resultado);

} catch (error) {
    if (error instanceof TypeError)
        console.error("TypeError: " + error.message);
    else
        console.error("Erro: " + error);
} finally {
    console.log("O try-catch capturou o erro!");
}

export function converte(conteudo: any): string{
    return conteudo.toUpperCase();
}
```

<img src="https://i.imgur.com/V2ReOnx.png" title="source: imgur.com" width="3%"/>**Resultado do Algoritmo:**

```bash
TypeError: conteudo.toUpperCase is not a function
O try-catch capturou o erro!
```

Observe no resultado acima que a exceção: **TypeError** foi disparada, mas desta vez foi exibido o tipo de erro e o porque o erro foi disparado. 

Note que construímos um Laço Condicional para checar se o erro foi tipo **TypeError**, através da instrução **instance of**, que também identifica o tipo do erro disparado, mas com a vantagem de nos permitir selecionar qual ou quais propriedades do objeto **error** nós queremos exibir na tela. Observe que no comando **console.error()**, foi definido que será exibido apenas a propriedade **message**, que é a causa do erro **TypeError** ter sido disparado. Caso o erro seja de outro tipo ou de um tipo não identificado, será exibida uma mensagem diferente.

Como implementamos o Bloco Finally, uma mensagem adicional foi exibida no final da execução do código. Esta mensagem será exibida independente de uma Exception ser ou não disparada.

<br />

<div align="left"><img src="https://i.imgur.com/r9lrbPG.png" title="source: imgur.com" width="4%"/> <a href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/try...catch" target="_blank"><b>Documentação: Try..Catch..Finally</b></a></div>

<div align="left"><img src="https://i.imgur.com/r9lrbPG.png" title="source: imgur.com" width="4%"/> <a href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Errors/Not_a_function" target="_blank"><b>Documentação: TypeError: x is not a function.</b></a></div>

<br />

<h2>3. A Classe Error</h2>



Como vimos no exemplo anterior, foi tratada 1 Exceção dentro da aplicação: **TypeError**. Entretanto, você deve estar se perguntando de onde veio esta Exceção? A resposta é a Classe **Error**, que é responsável por definir as Exceções padrões do JavaScript e do TypeScript. A Classe Error também é conhecida como **Classe de Erros Integrados**. Veja na imagem abaixo, a hierarquia da Classe **Error**, com os seus 7 tipos de Exceções e alguns exemplos de mensagens erro, que se enquadram em cada tipo:

<div align="center"><img src="https://i.imgur.com/T77ULCM.png" title="source: imgur.com" /></div>

A Classe **Error** também é utilizada como a Classe Base para outras Sub Classes de erro. Estas Sub Classes representam diferentes tipos de erros que podem ocorrer em um código JavaScript/TypeScript. Além disso, elas possuem nome próprio e propriedades, que emitem mensagens específicas, de acordo com a exceção lançada. Veja na lista abaixo os 6 tipos diferentes de exceções, mapeadas pela Classe Error:

- **SyntaxError:** Representa um erro de sintaxe, que ocorre ao analisar o código. Se escrevermos o código com a sintaxe errada, o TypeScript gerará um erro do tipo **Syntax Error**.
- **TypeError:** Indica que uma operação ou função foi executada em um tipo incompatível. Quando ocorre um problema de incompatibilidade de tipo de variável ou do tipo de retorno da função, o TypeScript gerará um erro do tipo **Type Error**.
- **ReferenceError:** Ocorre quando uma referência inválida é feita a uma variável ou função que não está definida. Se tentarmos acessar uma variável sem declarar antes, o TypeScript gerará um erro do tipo **Reference Error**. 
- **RangeError:** Indica que um valor numérico está fora do intervalo permitido. Se tentarmos acessar algo que está fora de um intervalo pré definido, o TypeScript gerará um erro do tipo **Range Error**. 
- **URIError:** Ocorre ao codificar ou decodificar funções e neste processo encontram strings URI malformadas. Este erro geralmente acontece ao passar um parâmetro inválido para a função **decodeURI()**, o que fará o TypeScript gerar um erro do tipo **URI Error**.
- **EvalError:** Representa erros que ocorrem durante a execução da função global eval(). Esta exceção não é mais lançada porque não é recomendado utilizar a função **eval()** por questões de segurança da aplicação. Entretanto, a exceção **EvalError** permanece ativa por questões de compatibilidade com códigos mais antigos.
- **InternalError:** indica um erro que ocorreu internamente no Transpilador TypeScript ou no Mecanismo JavaScript. Como esta exceção não segue os padrões, é recomendado não utilizar em Websites, porque ele não funcionará em todos os Navegadores WEB.

Para consultar as mensagens de erro, que podem ser geradas por cada tipo de erro, acesse os links abaixo:

<br />

<div align="left"><img src="https://i.imgur.com/r9lrbPG.png" title="source: imgur.com" width="4%"/> <a href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Error" target="_blank"><b>Documentação: Tipos de Erro - Classe Error.</b></a></div>

<div align="left"><img src="https://i.imgur.com/r9lrbPG.png" title="source: imgur.com" width="4%"/> <a href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Errors" target="_blank"><b>Documentação: Lista de Mensagens de Erro - Classe Error.</b></a></div>

<br />


<h2>4. Throw</h2>



A **Cláusula throw lança uma exceção definida pelo usuário em qualquer ponto do código**. A execução da função atual vai parar (as instruções após o throw não serão executadas), e o controle será passado para o primeiro bloco catch na pilha de chamadas. Se nenhum bloco catch existe entre as funções "chamadoras", o programa será finalizado.

**Sintaxe:**

```ts
throw new Tipo_Erro("Mensagem");
```

<br />

<img src="https://i.imgur.com/8eYS3Y6.png" title="source: imgur.com" width="3%"/>**Exemplo 04 - Cláusula Throw - Versão 01:** 

No exemplo abaixo, vamos construir uma aplicação para checar se uma pessoa está apta a dirigir:

```ts
import readline = require("readline-sync");

try {
    
    let idade: number = readline.questionFloat("Digite a idade da Pessoa: ");

    validarIdade(idade);

} catch (error) {
    console.error("Erro:" + error);
}

function validarIdade(idade: number): void {

    if (idade < 18)
        throw new Error("A Pessoa não está apta a dirigir!");
    else
        console.log("A Pessoa está apta a dirigir!");

}
```

Execute o código acima e digite um valor menor do que 18 anos. O resultado você confere abaixo:

<img src="https://i.imgur.com/V2ReOnx.png" title="source: imgur.com" width="3%"/>**Resultado do Algoritmo:**

```bash
Digite a idade da Pessoa: 12
Erro:Error: A Pessoa não está apta a dirigir!
```

<br />

Observe que a exceção: **Error** foi disparada dentro do Método **validarIdade()**, exibindo a mensagem do erro, que foi definida pela pessoa desenvolvedora e o programa foi finalizado na sequência.

Ao executar a instrução **throw**, o programa tenta encontrar algum bloco **try**, que possua instrução **catch** correspondente ao tipo de exceção que foi lançada. Se encontrar uma correspondência, o controle será transferido para essa instrução, caso contrário o programa será finalizado. Vamos atualizar este código inserindo um Bloco **try...catch**.

<br />

<img src="https://i.imgur.com/8eYS3Y6.png" title="source: imgur.com" width="3%"/>**Exemplo 05 - Cláusula Throw - Versão 2:** 

```ts
import readline = require("readline-sync");

let loop: boolean = true;

do {
    try {

        let idade: number = readline.questionFloat("Digite a idade da Pessoa: ");

        validarIdade(idade);

        loop = false;

    } catch (error) {
        if (error instanceof Error)
            console.error("Erro: Digite um número inteiro maior ou igual a 18!");
        else
            console.error("Erro:" + error);
    }
} while (loop);

function validarIdade(idade: number): void {

    if (idade < 18)
        throw new Error("A Pessoa não está apta a dirigir!");
    else
        console.log("A Pessoa está apta a dirigir!");

}
```

Execute o código acima e digite um valor menor do que 18 anos. O resultado você confere abaixo:

<img src="https://i.imgur.com/V2ReOnx.png" title="source: imgur.com" width="3%"/>**Resultado do Algoritmo:**

```bash
Digite uma idade: 
12

Digite um número inteiro maior ou igual a 18!

Digite uma idade:_ 
```

<br />

Observe que a exceção: **Error** foi disparada dentro do Método **validarIdade()**, mas desta vez foi exibida uma outra mensagem personalizada: *"Digite um número inteiro maior ou igual a 18!"*. Além disso, o controle sobre o que fazer com o erro, foi transferido para o Bloco **try...catch**, que solicita ao usuário que digite uma nova idade maior ou igual a 18. Como foi implementado um Laço de repetição **do...while**, este processo se repetirá até que o usuário digite uma idade maior ou igual a 18.

Apesar do JavaScript/TypeScript fornecer o método **throw** para gerar exceções definidas pelo usuário, quando se trata de erros específicos de aplicativos, uma alternativa mais eficaz é estender a classe genérica Error e criar uma exceção personalizada. Com um objeto de erro personalizado, você pode criar seu próprio código e mensagem de erro.

<br />

<img src="https://i.imgur.com/8eYS3Y6.png" title="source: imgur.com" width="3%"/>**Exemplo 06 - Exceção personalizada:** 

Vamos criar uma nova pasta chamada **excecao_simples**, dentro da pasta **exceptions** e inserir a **Classe ExcecaoSimples** (Exceção personalizada), que será uma Classe do tipo Error, criada pela pessoa desenvolvedora:

1. Na **Barra Explorer**, selecione a pasta **typescript** e clique no botão **New Folder** (Nova Pasta), indicado na imagem abaixo: 

<div align="center"><img src="https://i.imgur.com/ZmAVySi.png" title="source: imgur.com" /></div>

2. O nome da pasta será **exceptions**, como mostra a imagem abaixo. Após digitar o nome da pasta, pressione a tecla **enter** do seu teclado para concluir. 

<div align="center"><img src="https://i.imgur.com/RIdZGjG.png" title="source: imgur.com" /></div>

3. Na **Barra Explorer**, selecione a pasta **exceptions** lique no botão **New Folder** (Nova Pasta), indicado na imagem abaixo: 

<div align="center"><img src="https://i.imgur.com/ppDBbhv.png" title="source: imgur.com" /></div>

4. O nome da pasta será **excecao_simples**, como mostra a imagem abaixo. Após digitar o nome da pasta, pressione a tecla **enter** do seu teclado para concluir. 

<div align="center"><img src="https://i.imgur.com/5YrUVwe.png" title="source: imgur.com" /></div>

Na sequência, vamos criar o arquivo **ExcecaoSimples.ts**, dentro da nossa pasta **excecao_simples**:

1. Selecione a pasta **excecao_simples** e clique no botão **New File** (Novo Arquivo), indicado na imagem abaixo:  

<div align="center"><img src="https://i.imgur.com/k5FmbnF.png" title="source: imgur.com" /></div>

2. O nome do arquivo será **ExcecaoSimples.ts**, como mostra a figura abaixo. Após digitar o nome do arquivo, pressione a tecla **enter** do seu teclado para concluir. 

<div align="center"><img src="https://i.imgur.com/lfrfDDM.png" title="source: imgur.com" /></div>

<br />

1. Insira o código abaixo na Classe **ExcecaoSimples**:

```ts
export class ExcecaoSimples extends Error {

    constructor(message: string) {
        super();
        this.name = 'Exceção Simples'
        this.message = message;
    }
}
```

A Classe **ExcecaoSimples** foi definida como uma herança da Classe **Error**. Observe que foi criados 1 Método Construtor, com o parâmetro **message**, que permite personalizar a mensagem de erro.


Na sequência, vamos criar a Classe **TestaExcecao.ts**, dentro da pasta **excecao_simples**, para testarmos a nossa Classe **ExcecaoSimples**:

1. Selecione a pasta **excecao_simples** e clique no botão **New File** (Novo Arquivo), indicado na imagem abaixo:  

<div align="center"><img src="https://i.imgur.com/k5FmbnF.png" title="source: imgur.com" /></div>

2. O nome do arquivo será **TestaExcecao.ts**, como mostra a figura abaixo. Após digitar o nome do arquivo, pressione a tecla **enter** do seu teclado para concluir. 

<div align="center"><img src="https://i.imgur.com/rZ1w7wM.png" title="source: imgur.com" /></div>

5. Insira o código abaixo na **Classe TestaExcecao**:

```ts
import readline = require("readline-sync");
import { ExcecaoSimples } from './ExcecaoSimples';

let resultado: number | null;
let loop: boolean = true;

do {
    try {
        let numero1: number = readline.questionFloat("Digite o primeiro numero: ");
        let numero2: number = readline.questionFloat("Digite o segundo numero: ");

        resultado = dividir(numero1, numero2);

        console.log("O Resultado da divisão é: " + resultado);

        loop = false;

    } catch (error) {
        console.error("Erro: " + error);
    }
} while (loop);

function dividir(numero1: number, numero2: number): number | null {

    if (numero2 == 0)
        throw new ExcecaoSimples("Não existe divisão por zero!");

    return numero1 / numero2;
}
```

<img src="https://i.imgur.com/V2ReOnx.png" title="source: imgur.com" width="3%"/>**Resultado do Algoritmo:**

```bash
Digite o primeiro numero: 10
Digite o segundo numero: 0
Erro: Exceção Simples: Não existe divisão por zero!
Digite o primeiro numero: 10
Digite o segundo numero: 2
O Resultado da divisão é: 5
```

<br />

<div align="left"><img src="https://i.imgur.com/r9lrbPG.png" title="source: imgur.com" width="4%"/> <a href="https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/throw" target="_blank"><b>Documentação: throw.</b></a></div>

<br />

<h2>5. Por que devemos tratar as Exceções?</h2>



Quando uma Exceção é tratada, estamos oferecendo alguma forma alternativa para continuar a execução do programa sem que ele seja finalizado devido ao erro. O tratamento de exceções desempenha um papel importante no desenvolvimento de uma aplicação concisa, limpa, legível e de fácil manutenção. 

<br />

<div align="left"><img src="https://i.imgur.com/JACNZiR.png" title="source: imgur.com" width="5%"/> <a href="https://github.com/rafaelq80/exemplos_js/tree/main/typescript/exceptions" target="_blank"><b>Código fonte dos Exemplos</b></a></div>

<br />

------

## 🔑**Pontos chave:**

1. **Exceções** em TypeScript são classes especiais utilizadas para manipular erros que podem surgir durante a execução.
2. *O* **bloco try/catch/finally** permite capturar exceções que podem ocorrer quando uma parcela de código ou função é executada.
3. A **cláusula throw lança uma exceção em qualquer ponto do código**. 
5. Você também pode criar e lançar exceções personalizadas.

<br /><br />

<div align="left"><a href="README.md"><img src="https://i.imgur.com/XMgF3gl.png" title="source: imgur.com" width="3%"/>Voltar</a></div>
